default_game = mineclone2
server_name = El Servidor de Mita
server_description = Server running VoxeLibre (Mineclone2)
port = 30000
name = mita
motd = ¡Bienvenido a El Servidor de Mita! Server running VoxeLibre (Mineclone2).
server_announce = true
enable_music = false
